# general settings
name: asr
model_type: ASR21cmModel
# scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0
use_amp: true

# dataset and data loader settings
datasets:
  train:
    name: T21train
    type: Custom21cmDataset
    dataroot_gt: /home/sp2053/rds/hpc-work/ASR21cm/datasets/varying_IC/T21_cubes/
    dataroot_IC: /home/sp2053/rds/hpc-work/ASR21cm/datasets/varying_IC/IC_cubes/
    redshifts: [10,]
    IC_seeds: [0,]
    Npix: 256
    cut_factor: 1
    scale_max: 4.5
    scale_min: 1.1
    n_augment: 1
    one_box: true
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: T21val
    type: Custom21cmDataset
    dataroot_gt: /home/sp2053/rds/hpc-work/ASR21cm/datasets/varying_IC/T21_cubes
    dataroot_IC: /home/sp2053/rds/hpc-work/ASR21cm/datasets/varying_IC/IC_cubes
    redshifts: [10,]
    IC_seeds: [2, 3]
    Npix: 256
    cut_factor: 0
    scale_max: 4.5
    scale_min: 1.1
    n_augment: 1
    one_box: false
    io_backend:
      type: disk

# network structures
network_g:
  # hr_size: 128 # Npix / 2**cut_factor
  type: ArSSR
  dim: 4 #  8
  decoder_depth: 4 # 4
  decoder_width: 8 # 8
  use_checkpoint: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  total_iter: 1000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: L1Loss
    loss_weight: 1.0

# validation settings (temporarily disabled)
val:
 val_freq: !!float 5e3
 save_img: true
 metrics:
  rmse:
    type: calculate_rmse

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
