# general settings
name: diffusion
model_type: ScoreDiffusionVPSDEModel
num_gpu: 1  # Using 1 GPU - multi-GPU overhead too high for small model
manual_seed: 0

beta_max: 20.0
beta_min: 0.
epsilon_t: !!float 1e-5

# dataset and data loader settings
datasets:
  train:
    name: T21train
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [14,]
    IC_seeds: [20,]
    gt_size: 128
    Npix: 256
    load_full_dataset: true
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2  # Lower since data is in memory
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 20
    prefetch_mode: ~

  val:
    name: T21val
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    redshifts: [14,]
    IC_seeds: [20,]
    gt_size: 128
    Npix: 256
    io_backend:
      type: disk

# network structures
network_g:
  type: SongUNet
  img_resolution: 128
  in_channels: 4
  out_channels: 1
  label_dim: 0
  augment_dim: 0
  model_channels: 8
  channel_mult: [1,2,4,8,16]
  num_blocks: 2
  attn_resolutions: [8,]  # Attention at innermost level

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: !!float 1e-3
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000, 40000]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: VPLoss #MSELoss
    #reduction: sum

# validation settings (temporarily disabled)
val:
 val_freq: !!float 1e3
 save_img: true
 metrics:
  rmse:
    type: calculate_rmse
    better: 'lower'

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
