# general settings
name: diffusion_vpred_redshift_200M_2
model_type: ScoreDiffusionVPSDEvpredModel
num_gpu: auto  # Using 1 GPU - multi-GPU overhead too high for small model
manual_seed: 0

beta_max: 12.0
beta_min: 0.1
epsilon_t: !!float 1e-3

# dataset and data loader settings
datasets:
  train:
    name: T21train
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [10,11, 12,13,14, 15,16,17,18,19]
    IC_seeds: [0,1,2,3,4,5,6,7,8,9]
    gt_size: 64
    Npix: 256
    load_full_dataset: true
    preload_to_gpu: true  # Use CPU preloading for multi-GPU compatibility
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0  # Set to 0 when preload_to_gpu and load_full_dataset=true (data already in memory) else 4-8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 16
    prefetch_mode: ~

  val_redshift_10:
    name: val_z10
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [10,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_11:
    name: val_z11
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [11,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_12:
    name: val_z12
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [12,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_13:
    name: val_z13
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [13,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_14:
    name: val_z14
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [14,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_15:
    name: val_z15
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [15,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_16:
    name: val_z16
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [16,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_17:
    name: val_z17
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [17,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_18:
    name: val_z18
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [18,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

  val_redshift_19:
    name: val_z19
    type: FixedScale21cmDataset
    dataroot_gt: datasets/varying_IC/T21_cubes
    dataroot_IC: datasets/varying_IC/IC_cubes
    scale: 4
    redshifts: [19,]
    IC_seeds: [10,]
    gt_size: 64
    Npix: 256
    io_backend:
      type: disk

# network structures
network_g:
  type: SongUNet
  img_resolution: 64
  in_channels: 4
  out_channels: 1
  label_dim: 1
  augment_dim: 0
  model_channels: 128
  channel_mult: [1,2,2,4]
  num_blocks: 2
  attn_resolutions: [8,]  # Attention at innermost level

# path
path:
  pretrain_network_g: experiments/diffusion_vpred_redshift_200M_2/models/net_g_28000.pth
  strict_load_g: true
  resume_state: experiments/diffusion_vpred_redshift_200M_2/training_states/28000.state

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 2e-5
    weight_decay: !!float 1e-5
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [8000,]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: 1000  # no warm up is -1
  grad_clip: 6.0  # Gradient clipping to prevent explosion

  # losses
  pixel_opt:
    type: MSELoss
    #reduction: sum

# validation settings (temporarily disabled)
val:
 val_freq: !!float 2e3
 save_img: true
 metrics:
  rmse:
    type: calculate_rmse
    better: 'lower'
  rmse_dsq:
    type: calculate_rmse_dsq
    better: 'lower'

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
